# Generated by Django 5.0.4 on 2024-07-30 18:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobileStore_product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده /نشده')),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ایجاد سبد')),
                ('j_create_date', django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ایجاد سبد شمسی')),
                ('j_payment_date', django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ پرداخت سبد شمسی')),
                ('is_send', models.BooleanField(default=False, verbose_name='ارسال شده/نشده')),
                ('codeFolowed', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{25}$')], verbose_name='کد رهگیری')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_order.order', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات محصول',
                'verbose_name_plural': 'اطلاعات جزئیات محصولات',
            },
        ),
    ]
