# Generated by Django 5.0.4 on 2024-05-13 18:14

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_order', '0002_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='j_create_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ ایجاد سبد شمسی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='j_payment_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد سبد شمسی'),
        ),
    ]
