# Generated by Django 5.0.4 on 2024-05-13 18:18

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_order', '0003_order_j_create_date_alter_order_j_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='j_payment_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ پرداخت سبد شمسی'),
        ),
    ]
