# Generated by Django 5.0.4 on 2024-07-30 19:17

import django.db.models.deletion
import mobileStore_Founders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام اواتار')),
                ('position', models.CharField(max_length=150, verbose_name='جایگاه اواتار')),
                ('description', models.TextField(verbose_name='توضیحات اواتار')),
                ('image', models.ImageField(blank=True, null=True, upload_to=mobileStore_Founders.models.upload_image_path, verbose_name='تصویر اواتار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مؤسس',
                'verbose_name_plural': 'مؤسس ها',
            },
        ),
    ]
