# Generated by Django 4.1.12 on 2024-01-15 17:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mobileStore_product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileStore_product_category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('code', models.CharField(max_length=150, verbose_name='کد')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='مکان کالا')),
                ('number', models.CharField(blank=True, max_length=150, null=True, verbose_name='تعداد')),
                ('brand', models.CharField(blank=True, max_length=150, null=True, verbose_name='برند')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('smallDescription', models.TextField(max_length=150, verbose_name='کوتاه توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('priceOff', models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to=mobileStore_product.models.upload_image_path, verbose_name='تصویر')),
                ('mobile_image_tumpnail', models.ImageField(blank=True, null=True, upload_to=mobileStore_product.models.upload_mobile_image_tumpnail_path, verbose_name='تصویر_بند_انگشتی')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید ها')),
                ('vige', models.BooleanField(default=False, verbose_name='ویژه / غیرویژه')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='mobileStore_product_category.productcategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ستاره',
                'verbose_name_plural': 'ستاره ها',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=mobileStore_product.models.upload_gallery_image_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پسندیدن',
                'verbose_name_plural': 'پسندیدن',
            },
        ),
    ]
