# Generated by Django 5.0.4 on 2024-07-30 19:06

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import mobileStore_product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobileStore_product_category', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='کد')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='مکان کالا')),
                ('number', models.CharField(blank=True, max_length=150, null=True, verbose_name='تعداد')),
                ('brand', models.CharField(blank=True, max_length=150, null=True, verbose_name='برند')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('smallDescription', models.TextField(max_length=150, verbose_name='کوتاه توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('priceOff', models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to=mobileStore_product.models.upload_image_path, verbose_name='تصویر')),
                ('mobile_image_tumpnail', models.ImageField(blank=True, null=True, upload_to=mobileStore_product.models.upload_mobile_image_tumpnail_path, verbose_name='تصویر_بند_انگشتی')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('visit_count', models.IntegerField(default=0, verbose_name='تعداد بازدید ها')),
                ('vige', models.BooleanField(default=False, verbose_name='ویژه / غیرویژه')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='ralet', to='mobileStore_product_category.productcategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد پیام شمسی')),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='تاریخ تغییر پیام شمسی')),
                ('is_ok', models.BooleanField(default=False, verbose_name='تایید شده / نشده')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mobileStore_product.customercomment', verbose_name='زیر دسته')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر پیام')),
                ('CommentProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product', verbose_name='محصول پیام')),
            ],
            options={
                'verbose_name': ' نظرات کاربران ',
                'verbose_name_plural': 'نظرات در مورد کالا کاربران',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to=mobileStore_product.models.upload_gallery_image_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ستاره',
                'verbose_name_plural': 'ستاره ها',
            },
        ),
        migrations.CreateModel(
            name='LikesCustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('CustomerComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.customercomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پسندیدن نظرات',
                'verbose_name_plural': 'پسندیدن نظرات',
                'unique_together': {('user', 'CustomerComment')},
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product')),
            ],
            options={
                'verbose_name': 'پسندیدن',
                'verbose_name_plural': 'پسندیدن',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
