# Generated by Django 4.1.12 on 2024-01-26 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileStore_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'product')},
        ),
    ]
