# Generated by Django 4.1.12 on 2024-02-14 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileStore_product', '0002_alter_likes_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان پیام')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('is_ok', models.BooleanField(default=False, verbose_name='تایید شده / نشده')),
                ('CommentProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.product')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mobileStore_product.customercomment', verbose_name='زیر دسته')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ' نظرات کاربران ',
                'verbose_name_plural': 'نظرات در مورد کالا کاربران',
            },
        ),
    ]
