# Generated by Django 4.1.12 on 2024-02-14 18:35

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_product', '0005_alter_customercomment_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomment',
            name='updated',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ تغییر سبد شمسی'),
        ),
    ]
