# Generated by Django 4.1.12 on 2024-02-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_product', '0009_alter_customercomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomment',
            name='subject',
        ),
    ]
