# Generated by Django 4.1.12 on 2024-02-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_product', '0012_alter_customercomment_commentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mobileStore_product.customercomment', verbose_name='زیر دسته'),
        ),
    ]
