# Generated by Django 4.1.12 on 2024-02-21 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileStore_product', '0013_alter_customercomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesCustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('CustomerComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.customercomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پسندیدن نظرات',
                'verbose_name_plural': 'پسندیدن نظرات',
                'unique_together': {('user', 'CustomerComment')},
            },
        ),
    ]
