# Generated by Django 4.1.12 on 2024-02-25 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileStore_product', '0016_remove_likescustomercomment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likescustomercomment',
            name='CustomerComment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.customercomment'),
        ),
        migrations.AlterField(
            model_name='likescustomercomment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
