# Generated by Django 4.1.12 on 2024-02-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_product', '0017_alter_likescustomercomment_customercomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likescustomercomment',
            name='CustomerComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_product.customercomment'),
        ),
    ]
