# Generated by Django 4.1.12 on 2024-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_product_category', '__first__'),
        ('mobileStore_product', '0019_alter_likescustomercomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ralet', to='mobileStore_product_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
