# Generated by Django 4.1.12 on 2024-03-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_product_category', '__first__'),
        ('mobileStore_product', '0020_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='ralet', to='mobileStore_product_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
