# Generated by Django 5.0.4 on 2024-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_product', '0021_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=150, unique=True, verbose_name='کد'),
        ),
    ]
