# Generated by Django 5.0.4 on 2024-08-23 12:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_order', '0001_initial'),
        ('post_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentDetails', models.CharField(choices=[('1', 'پرداخت توسط فیش بانکی'), ('2', 'زرین پال')], default=1, max_length=20, verbose_name='روش ارسال')),
                ('isTermsAndRules', models.BooleanField(default=False, verbose_name=' پذیرفتن شرایط ')),
                ('peymentCode', models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{25}$')], verbose_name=' کد پرداخت ')),
                ('OrderDetailSelected', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_order.order', verbose_name=' سبد خرید انتخابی انتخابی ')),
            ],
            options={
                'verbose_name': 'جزئیات پرداخت',
                'verbose_name_plural': 'جرئیات پرداخت',
            },
        ),
    ]
