# Generated by Django 5.0.4 on 2024-08-23 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0002_paymentmethodedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodedetail',
            name='peymentCode',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')], verbose_name=' کد پرداخت '),
        ),
    ]
