# Generated by Django 5.0.4 on 2024-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_information', '0003_alter_paymentmethodedetail_peymentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodedetail',
            name='peymentCode',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' کد پرداخت '),
        ),
    ]
