# Generated by Django 5.0.4 on 2024-08-23 13:09

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileStore_order', '0001_initial'),
        ('post_information', '0004_alter_paymentmethodedetail_peymentcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('post_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اطلاعات پست',
                'verbose_name_plural': 'اطلاعات پست',
            },
        ),
        migrations.CreateModel(
            name='PostAddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrierDetails', models.CharField(choices=[('1', 'پست'), ('2', 'تیپاکس'), ('3', 'باربری')], default=1, max_length=20, verbose_name='روش ارسال')),
                ('isResive', models.BooleanField(default=False)),
                ('carried', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ حمل شده')),
                ('sentToShippingUnit', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال شده به واحد حمل')),
                ('collected', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ جمع آوری شده')),
                ('collecting', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ در حال جمع اوری')),
                ('Ongoing', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ در دست اقدام')),
                ('processing', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ در حال پردازش')),
                ('confirmedPayment', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت تایید شده')),
                ('OrderDetailSelected', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobileStore_order.order', verbose_name=' سبد خرید انتخابی  ')),
                ('addressSelected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_information.postaddress', verbose_name=' آدرس انتخابی ')),
            ],
            options={
                'verbose_name': 'اطلاعات آدرس انتخابی',
                'verbose_name_plural': 'اطلاعات آدرس',
            },
        ),
    ]
