# Generated by Django 5.0.4 on 2024-10-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_information", "0006_postaddressdetail_postpriceselected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postaddressdetail",
            name="PostPriceSelected",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="post_information.postprice",
                verbose_name=" هزینه ارسال انتخابی ",
            ),
        ),
    ]
