# Generated by Django 5.0.4 on 2024-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_information", "0007_alter_postaddressdetail_postpriceselected"),
    ]

    operations = [
        migrations.AddField(
            model_name="postaddressdetail",
            name="trackingNumber",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="شماره پیگیری"
            ),
        ),
    ]
