# Generated by Django 5.0.4 on 2024-10-05 15:54

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_information", "0008_postaddressdetail_trackingnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethodedetail",
            name="peymentDate",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="تاریخ پرداخت"
            ),
        ),
    ]
