# Generated by Django 5.0.4 on 2024-11-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_information", "0009_paymentmethodedetail_peymentdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethodedetail",
            name="TermsAndRules_field",
            field=models.TextField(blank=True, null=True, verbose_name=" شرایط "),
        ),
        migrations.AlterField(
            model_name="paymentmethodedetail",
            name="PaymentDetails",
            field=models.CharField(
                choices=[("1", "پرداخت توسط فیش بانکی"), ("2", "زرین پال")],
                default=1,
                max_length=20,
                verbose_name="روش پرداخت",
            ),
        ),
    ]
