# Generated by Django 5.0.4 on 2024-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_information", "0011_remove_paymentmethodedetail_termsandrules_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethodedetail",
            name="PaymentDetails",
            field=models.CharField(max_length=20, verbose_name="روش پرداخت"),
        ),
        migrations.AlterField(
            model_name="postaddressdetail",
            name="carrierDetails",
            field=models.CharField(max_length=20, verbose_name="روش ارسال"),
        ),
    ]
